database:
  name: carrpigeo
  host: postgres
  port: 5432
  user: carrpigeo_user
  password: carrpigeo_9876
  sslmode: disable
  maxOpenConns: 10
  maxIdleConns: 10
  maxIdleTime: 15m
httpServer:
  address: 0.0.0.0:2500
  idleTimeout: 90s
  readTimeout: 10s
  writeTimeout: 20s
smtp:
  host: smtp.gmail.com
  port: 587
  user: [EMAIL_ADDRESS]
  password: [PASSWORD]
log:
  logPath: ./storage/carrpigeo.log
